### PR TITLE
Removing duplicated code (metal.async).

### PR DESCRIPTION
**Pull request by henvic**

### CODE REVIEW

**Comment by henvic** [comment]
Export removed. CancellablePromise made the default exported object.

**Comment by mairatma** [comment]
I think it'd be best to export CancellablePromise both ways (default and named) for now, to prevent existing calls from breaking. We can later update modules that use metal-promise to use the default export and remove the named export then.

**Comment by henvic** [comment]
Done.

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Thanks!

**Pull request merged**
