### PR TITLE
minor - Updates from google source file. Fixes #7

### LINKED ISSUE #7: CancellablePromise.all(iterable) throws an error if a item of the iterable parameter is a boolean
According to the specification, the method all() is able to accept a boolean as one item of the iterable parameter. Metal-promise throws an error. 

`Uncaught TypeError: promise.then is not a function`

https://www.promisejs.org/api/

### PR DESCRIPTION
**Pull request by fernandosouza**
I'm planning to bring tests from the source repo in order to make sure any future additions will work properly. Actually, I already started, but I've realised it's going to take a lot of time to bring all of them, I think it's better I send it in another commit. What do you think, guys?

I ran the tests of `Senna`, `metal-router`, `auto-complete` and `metal-ajax`. All of them are ok.

### CODE REVIEW

**Comment by fernandosouza** [comment]
Hey @jbalsas. Yes. I didn't put those classes outside the file. But I'm sure it would be nice to have it. I will do it.

**Comment by jbalsas** [comment]
Or `FreeList` in... I don't have any preference, we can do one or the other 😂

**Comment by fernandosouza** [comment]
Don't you think that, for organising the code, it's preferable to put each class into its own file?

**Comment by jbalsas** [comment]
Yes, I do :)

**Comment by jbalsas** [comment]
I'm just worried about the amount of work and possible regressions that we could create if we do this before adding the tests...

**Comment by fernandosouza** [comment]
I see. But the implementation of the methods will remain the same. The only change will be moving the code to another file. `Thenable` is very small and `CancellablePromise` has its own implementation of `Resolver`, so, we can keep it in the same file.

**Comment by fernandosouza** [comment]
Hey, @brunobasto and @eduardolundgren. Do you have something to say about it?

**Comment by brunobasto** [comment]
Is it a lot of work to bring the tests  in? I'd rather have the peace of mind of having tests..

**Comment by fernandosouza** [comment]
It will take time to bring all of them at once. https://github.com/google/closure-library/blob/master/closure/goog/promise/promise_test.js

And what about move `thenable` class to its own file, @brunobasto?

**Comment by Robert-Frampton** [comment]
In revisiting this, it would indeed take a lot of work getting the tests to run in our environment, and then we would have to maintain 2000 lines of tests we didn't write.

@jbalsas what do you think about creating some of our own tests that cover our own use cases? We can still pull from some of closure's tests, but maybe we don't need all of them?

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, yeah, makes sense, let's just try to bring the new version and is and start adding tests for what we need to cover 🤞

**Comment by Robert-Frampton** [comment]
https://github.com/metal/metal-promise/pull/17

**Pull request closed without merging**
